### ISSUE TITLE
Various errors while resolving unresolved identifiers

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/metadata_wrangler#78]
Amy fixed a number of errors found while resolving unresolved identifiers but some common errors remain. Examples:

This error has happened for 11048 different identifiers:

```
2016-07-27 14:22:16,725:Identifier Resolution Manager:ERROR:monitor.py:FAILURE on Overdrive ID/db8f9a42-f694-40ab-819b-588aefc5c1e4 ID=4774484 prim_ed=288759 ("The Jet-Set Seduction"): Traceback (most recent call last):
  File "/home/ec2-user/metadata/core/monitor.py", line 138, in resolve_and_handle_result
    self.resolve(unresolved_identifier)
  File "/home/ec2-user/metadata/core/monitor.py", line 174, in resolve
    self.finalize(unresolved_identifier)
  File "/home/ec2-user/metadata/monitor.py", line 109, in finalize
    self.resolve_equivalent_oclc_identifiers(identifier)
  File "/home/ec2-user/metadata/monitor.py", line 152, in resolve_equivalent_oclc_identifiers
    self.oclc_linked_data.ensure_coverage(oclc_id)
  File "/home/ec2-user/metadata/core/coverage.py", line 427, in ensure_coverage
    [identifier]
  File "/home/ec2-user/metadata/core/coverage.py", line 227, in process_batch_and_handle_results
    results = self.process_batch(batch)
  File "/home/ec2-user/metadata/core/coverage.py", line 299, in process_batch
    result = self.process_item(item)
  File "/home/ec2-user/metadata/oclc.py", line 1305, in process_item
    metadata.apply(edition)
  File "/home/ec2-user/metadata/core/metadata_layer.py", line 1251, in apply
    replace.contributions)
  File "/home/ec2-user/metadata/core/metadata_layer.py", line 1440, in update_contributions
    _db, self.identifiers, metadata_client
  File "/home/ec2-user/metadata/core/metadata_layer.py", line 200, in find_sort_name
    "Cannot find sort name for a contributor with no display name!"
ValueError: Cannot find sort name for a contributor with no display name!
```

There's also a failure that sometimes happens when recording another failure. This has happened 1262 times:

```
2016-07-27 12:54:29,242:Identifier Resolution Manager:ERROR:monitor.py:FAILURE on Overdrive ID/87b3a9de-b3d9-484a-870f-273b88bee154 ID=5129617 prim_ed=389822 ("Кто бы мог подумать! Как мозг заставляет нас делать глупости"): Traceback (most recent call last):
  File "/home/ec2-user/metadata/core/monitor.py", line 138, in resolve_and_handle_result
    self.resolve(unresolved_identifier)
  File "/home/ec2-user/metadata/core/monitor.py", line 174, in resolve
    self.finalize(unresolved_identifier)
  File "/home/ec2-user/metadata/monitor.py", line 109, in finalize
    self.resolve_equivalent_oclc_identifiers(identifier)
  File "/home/ec2-user/metadata/monitor.py", line 152, in resolve_equivalent_oclc_identifiers
    self.oclc_linked_data.ensure_coverage(oclc_id)
  File "/home/ec2-user/metadata/core/coverage.py", line 427, in ensure_coverage
    [identifier]
  File "/home/ec2-user/metadata/core/coverage.py", line 239, in process_batch_and_handle_results
    record = self.record_failure_as_coverage_record(item)
  File "/home/ec2-user/metadata/core/coverage.py", line 652, in record_failure_as_coverage_record
    return failure.to_coverage_record(operation=self.operation)
  File "/home/ec2-user/metadata/core/coverage.py", line 44, in to_coverage_record
    self.obj, self.data_source, operation=operation
  File "/home/ec2-user/metadata/core/model.py", line 1004, in add_for
    _db = Session.object_session(edition)
  File "/home/ec2-user/metadata/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 77, in object_session
    return object_session(instance)
  File "/home/ec2-user/metadata/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2787, in object_session
    raise exc.UnmappedInstanceError(instance)
UnmappedInstanceError: Class 'oclc.LinkedDataCoverageProvider' is not mapped
```

There are a few other problems that are smaller. I found the biggest problems by running this query against the metadata database:

```
select count(id), exception from unresolvedidentifiers where exception not like order by count(id) desc;
```

**Comment by aslagle** [comment]
`Class 'oclc.LinkedDataCoverageProvider' is not mapped` is one of the ones I fixed.

**Comment by leonardr** [comment]
:( I'm still seeing it on code that has your fixes. Could there be a second place where the same problem happens? This part of oclc.py looks like it might cause the problem.

```
                return CoverageFailure(
                    self, identifier, exception, transient=False
                )
```

**Comment by aslagle** [comment]
You're right - I fixed the CoverageFailure two lines below that but somehow missed that one :(

**Comment by leonardr** [comment]
I'm working on this.

**Comment by courte** [comment]
I think both of these have been fully resolved by past and recent changes, but I want to wait until we deploy and resolve a bunch of identifiers before closing.
